name: main
on: push
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'

            - name: Install dependencies
              run: pip install poetry

            - name: Set up project
              run: make install
            - name: Run tests
              run: make test
            - name: Run linter
              run: make lint

            - name: Test & publish code coverage
              uses: paambaati/codeclimate-action@v5.0.0
              if: github.ref_name == 'main'
              env:
                CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
              with:
                coverageCommand: make coverage-report
                debug: true