name: main
on: push
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: make install
            - run: make test
            - run: make lint